["fstream_std_format.cc"] # CI doesn't support <format>
ignore = true

["iobuf_file_std_format.cc"] # CI doesn't support <format>
ignore = true

["iobuf_file_std_format_locale.cc"] # CI doesn't support <format>
ignore = true

["fast_io_llvm_raw_fd_ostream_file_l10n.cc"] # no llvm env in CI
ignore = true

["fast_io_llvm_raw_fd_ostream_file.cc"] # no llvm env in CI
ignore = true

["llvm_raw_fd_ostream.cc"] # no llvm env in CI
ignore = true

["iobuf_file_lockable_big.cc"] # TODO: crash. why?
ignore = true

["iobuf_file_bin.cc"] # TODO: crash. why?
ignore = true

["iobuf_io_file_eol.cc"] # TODO: crash. why?
ignore = true

["iobuf_io_file_eol_dbg.cc"] # TODO: crash. why?
ignore = true

["iobuf_io_file_lf_crlf.cc"] # TODO: crash. why?
ignore = true

["iobuf_file_l10n.cc"] # TODO: locale unfinished
ignore = true
