["fast_io.cc"] # TODO: locale unfinished
ignore = true

["glibc_nl_langinfo.cc"] # TODO: CI runtime failed. why?
ignore = true
platform = "linux"

["put_time.cc"] # TODO: CI runtime failed. why?
ignore = true
platform = "linux"
